export const ABOUT_NEW_REQUEST = 'ABOUT_NEW_REQUEST';
export const ABOUT_NEW_SUCCESS = 'ABOUT_NEW_SUCCESS';
export const ABOUT_NEW_FAIL = 'ABOUT_NEW_FAIL';
export const ABOUT_NEW_RESET = 'ABOUT_NEW_RESET';

export const ABOUT_ALL_REQUEST = 'ABOUT_ALL_REQUEST';
export const ABOUT_ALL_SUCCESS = 'ABOUT_ALL_SUCCESS';
export const ABOUT_ALL_FAIL = 'ABOUT_ALL_FAIL';

export const ABOUT_BY_ID_REQUEST = 'ABOUT_BY_ID_REQUEST';
export const ABOUT_BY_ID_SUCCESS = 'ABOUT_BY_ID_SUCCESS';
export const ABOUT_BY_ID_FAIL = 'ABOUT_BY_ID_FAIL';
export const ABOUT_BY_ID_RESET = 'ABOUT_BY_ID_RESET';

export const ABOUT_UPDATE_BY_ID_REQUEST = 'ABOUT_UPDATE_BY_ID_REQUEST';
export const ABOUT_UPDATE_BY_ID_SUCCESS = 'ABOUT_UPDATE_BY_ID_SUCCESS';
export const ABOUT_UPDATE_BY_ID_FAIL = 'ABOUT_UPDATE_BY_ID_FAIL';
export const ABOUT_UPDATE_BY_ID_RESET = 'ABOUT_UPDATE_BY_ID_RESET';

export const ABOUT_DELETE_REQUEST = 'ABOUT_DELETE_REQUEST';
export const ABOUT_DELETE_SUCCESS = 'ABOUT_DELETE_SUCCESS';
export const ABOUT_DELETE_FAIL = 'ABOUT_DELETE_FAIL';
