export const CONTACT_NEW_REQUEST = 'CONTACT_NEW_REQUEST';
export const CONTACT_NEW_SUCCESS = 'CONTACT_NEW_SUCCESS';
export const CONTACT_NEW_FAIL = 'CONTACT_NEW_FAIL';
export const CONTACT_NEW_RESET = 'CONTACT_NEW_RESET';

export const CONTACT_ALL_REQUEST = 'CONTACT_ALL_REQUEST';
export const CONTACT_ALL_SUCCESS = 'CONTACT_ALL_SUCCESS';
export const CONTACT_ALL_FAIL = 'CONTACT_ALL_FAIL';

export const CONTACT_BY_ID_REQUEST = 'CONTACT_BY_ID_REQUEST';
export const CONTACT_BY_ID_SUCCESS = 'CONTACT_BY_ID_SUCCESS';
export const CONTACT_BY_ID_FAIL = 'CONTACT_BY_ID_FAIL';
export const CONTACT_BY_ID_RESET = 'CONTACT_BY_ID_RESET';

export const CONTACT_UPDATE_BY_ID_REQUEST = 'CONTACT_UPDATE_BY_ID_REQUEST';
export const CONTACT_UPDATE_BY_ID_SUCCESS = 'CONTACT_UPDATE_BY_ID_SUCCESS';
export const CONTACT_UPDATE_BY_ID_FAIL = 'CONTACT_UPDATE_BY_ID_FAIL';
export const CONTACT_UPDATE_BY_ID_RESET = 'CONTACT_UPDATE_BY_ID_RESET';

export const CONTACT_DELETE_REQUEST = 'CONTACT_DELETE_REQUEST';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAIL = 'CONTACT_DELETE_FAIL';
