export const INTRO_NEW_REQUEST = 'INTRO_NEW_REQUEST';
export const INTRO_NEW_SUCCESS = 'INTRO_NEW_SUCCESS';
export const INTRO_NEW_FAIL = 'INTRO_NEW_FAIL';
export const INTRO_NEW_RESET = 'INTRO_NEW_RESET';

export const INTRO_ALL_REQUEST = 'INTRO_ALL_REQUEST';
export const INTRO_ALL_SUCCESS = 'INTRO_ALL_SUCCESS';
export const INTRO_ALL_FAIL = 'INTRO_ALL_FAIL';

export const INTRO_BY_ID_REQUEST = 'INTRO_BY_ID_REQUEST';
export const INTRO_BY_ID_SUCCESS = 'INTRO_BY_ID_SUCCESS';
export const INTRO_BY_ID_FAIL = 'INTRO_BY_ID_FAIL';
export const INTRO_BY_ID_RESET = 'INTRO_BY_ID_RESET';

export const INTRO_UPDATE_BY_ID_REQUEST = 'INTRO_UPDATE_BY_ID_REQUEST';
export const INTRO_UPDATE_BY_ID_SUCCESS = 'INTRO_UPDATE_BY_ID_SUCCESS';
export const INTRO_UPDATE_BY_ID_FAIL = 'INTRO_UPDATE_BY_ID_FAIL';
export const INTRO_UPDATE_BY_ID_RESET = 'INTRO_UPDATE_BY_ID_RESET';

export const INTRO_DELETE_REQUEST = 'INTRO_DELETE_REQUEST';
export const INTRO_DELETE_SUCCESS = 'INTRO_DELETE_SUCCESS';
export const INTRO_DELETE_FAIL = 'INTRO_DELETE_FAIL';
