export const PROJECT_NEW_REQUEST = 'PROJECT_NEW_REQUEST';
export const PROJECT_NEW_SUCCESS = 'PROJECT_NEW_SUCCESS';
export const PROJECT_NEW_FAIL = 'PROJECT_NEW_FAIL';
export const PROJECT_NEW_RESET = 'PROJECT_NEW_RESET';

export const PROJECT_ALL_REQUEST = 'PROJECT_ALL_REQUEST';
export const PROJECT_ALL_SUCCESS = 'PROJECT_ALL_SUCCESS';
export const PROJECT_ALL_FAIL = 'PROJECT_ALL_FAIL';

export const PROJECT_BY_ID_REQUEST = 'PROJECT_BY_ID_REQUEST';
export const PROJECT_BY_ID_SUCCESS = 'PROJECT_BY_ID_SUCCESS';
export const PROJECT_BY_ID_FAIL = 'PROJECT_BY_ID_FAIL';
export const PROJECT_BY_ID_RESET = 'PROJECT_BY_ID_RESET';

export const PROJECT_UPDATE_BY_ID_REQUEST = 'PROJECT_UPDATE_BY_ID_REQUEST';
export const PROJECT_UPDATE_BY_ID_SUCCESS = 'PROJECT_UPDATE_BY_ID_SUCCESS';
export const PROJECT_UPDATE_BY_ID_FAIL = 'PROJECT_UPDATE_BY_ID_FAIL';
export const PROJECT_UPDATE_BY_ID_RESET = 'PROJECT_UPDATE_BY_ID_RESET';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

////////////// Project Image ///////////////////
export const PROJECT_IMAGE_NEW_REQUEST = 'PROJECT_IMAGE_NEW_REQUEST';
export const PROJECT_IMAGE_NEW_SUCCESS = 'PROJECT_IMAGE_NEW_SUCCESS';
export const PROJECT_IMAGE_NEW_FAIL = 'PROJECT_IMAGE_NEW_FAIL';
export const PROJECT_IMAGE_NEW_RESET = 'PROJECT_IMAGE_NEW_RESET';

export const PROJECT_IMAGE_DELETE_REQUEST = 'PROJECT_IMAGE_DELETE_REQUEST';
export const PROJECT_IMAGE_DELETE_SUCCESS = 'PROJECT_IMAGE_DELETE_SUCCESS';
export const PROJECT_IMAGE_DELETE_FAIL = 'PROJECT_IMAGE_DELETE_FAIL';
export const PROJECT_IMAGE_DELETE_RESET = 'PROJECT_IMAGE_DELETE_RESET';
