export const S_ATTRIBUTE_NEW_REQUEST = 'S_ATTRIBUTE_NEW_REQUEST';
export const S_ATTRIBUTE_NEW_SUCCESS = 'S_ATTRIBUTE_NEW_SUCCESS';
export const S_ATTRIBUTE_NEW_FAIL = 'S_ATTRIBUTE_NEW_FAIL';
export const S_ATTRIBUTE_NEW_RESET = 'S_ATTRIBUTE_NEW_RESET';

export const S_ATTRIBUTE_ALL_REQUEST = 'S_ATTRIBUTE_ALL_REQUEST';
export const S_ATTRIBUTE_ALL_SUCCESS = 'S_ATTRIBUTE_ALL_SUCCESS';
export const S_ATTRIBUTE_ALL_FAIL = 'S_ATTRIBUTE_ALL_FAIL';

export const S_ATTRIBUTE_BY_ID_REQUEST = 'S_ATTRIBUTE_BY_ID_REQUEST';
export const S_ATTRIBUTE_BY_ID_SUCCESS = 'S_ATTRIBUTE_BY_ID_SUCCESS';
export const S_ATTRIBUTE_BY_ID_FAIL = 'S_ATTRIBUTE_BY_ID_FAIL';
export const S_ATTRIBUTE_BY_ID_RESET = 'S_ATTRIBUTE_BY_ID_RESET';

export const S_ATTRIBUTE_UPDATE_BY_ID_REQUEST =
  'S_ATTRIBUTE_UPDATE_BY_ID_REQUEST';
export const S_ATTRIBUTE_UPDATE_BY_ID_SUCCESS =
  'S_ATTRIBUTE_UPDATE_BY_ID_SUCCESS';
export const S_ATTRIBUTE_UPDATE_BY_ID_FAIL = 'S_ATTRIBUTE_UPDATE_BY_ID_FAIL';
export const S_ATTRIBUTE_UPDATE_BY_ID_RESET = 'S_ATTRIBUTE_UPDATE_BY_ID_RESET';

export const S_ATTRIBUTE_DELETE_REQUEST = 'S_ATTRIBUTE_DELETE_REQUEST';
export const S_ATTRIBUTE_DELETE_SUCCESS = 'S_ATTRIBUTE_DELETE_SUCCESS';
export const S_ATTRIBUTE_DELETE_FAIL = 'S_ATTRIBUTE_DELETE_FAIL';
