export const SC_ATTRIBUTE_NEW_REQUEST = 'SC_ATTRIBUTE_NEW_REQUEST';
export const SC_ATTRIBUTE_NEW_SUCCESS = 'SC_ATTRIBUTE_NEW_SUCCESS';
export const SC_ATTRIBUTE_NEW_FAIL = 'SC_ATTRIBUTE_NEW_FAIL';
export const SC_ATTRIBUTE_NEW_RESET = 'SC_ATTRIBUTE_NEW_RESET';

export const SC_ATTRIBUTE_ALL_REQUEST = 'SC_ATTRIBUTE_ALL_REQUEST';
export const SC_ATTRIBUTE_ALL_SUCCESS = 'SC_ATTRIBUTE_ALL_SUCCESS';
export const SC_ATTRIBUTE_ALL_FAIL = 'SC_ATTRIBUTE_ALL_FAIL';

export const SC_ATTRIBUTE_BY_ID_REQUEST = 'SC_ATTRIBUTE_BY_ID_REQUEST';
export const SC_ATTRIBUTE_BY_ID_SUCCESS = 'SC_ATTRIBUTE_BY_ID_SUCCESS';
export const SC_ATTRIBUTE_BY_ID_FAIL = 'SC_ATTRIBUTE_BY_ID_FAIL';
export const SC_ATTRIBUTE_BY_ID_RESET = 'SC_ATTRIBUTE_BY_ID_RESET';

export const SC_ATTRIBUTE_UPDATE_BY_ID_REQUEST =
  'SC_ATTRIBUTE_UPDATE_BY_ID_REQUEST';
export const SC_ATTRIBUTE_UPDATE_BY_ID_SUCCESS =
  'SC_ATTRIBUTE_UPDATE_BY_ID_SUCCESS';
export const SC_ATTRIBUTE_UPDATE_BY_ID_FAIL = 'SC_ATTRIBUTE_UPDATE_BY_ID_FAIL';
export const SC_ATTRIBUTE_UPDATE_BY_ID_RESET =
  'SC_ATTRIBUTE_UPDATE_BY_ID_RESET';

export const SC_ATTRIBUTE_DELETE_REQUEST = 'SC_ATTRIBUTE_DELETE_REQUEST';
export const SC_ATTRIBUTE_DELETE_SUCCESS = 'SC_ATTRIBUTE_DELETE_SUCCESS';
export const SC_ATTRIBUTE_DELETE_FAIL = 'SC_ATTRIBUTE_DELETE_FAIL';
