export const SERVICE_NEW_REQUEST = 'SERVICE_NEW_REQUEST';
export const SERVICE_NEW_SUCCESS = 'SERVICE_NEW_SUCCESS';
export const SERVICE_NEW_FAIL = 'SERVICE_NEW_FAIL';
export const SERVICE_NEW_RESET = 'SERVICE_NEW_RESET';

export const SERVICE_ALL_REQUEST = 'SERVICE_ALL_REQUEST';
export const SERVICE_ALL_SUCCESS = 'SERVICE_ALL_SUCCESS';
export const SERVICE_ALL_FAIL = 'SERVICE_ALL_FAIL';

export const SERVICE_BY_ID_REQUEST = 'SERVICE_BY_ID_REQUEST';
export const SERVICE_BY_ID_SUCCESS = 'SERVICE_BY_ID_SUCCESS';
export const SERVICE_BY_ID_FAIL = 'SERVICE_BY_ID_FAIL';
export const SERVICE_BY_ID_RESET = 'SERVICE_BY_ID_RESET';

export const SERVICE_UPDATE_BY_ID_REQUEST = 'SERVICE_UPDATE_BY_ID_REQUEST';
export const SERVICE_UPDATE_BY_ID_SUCCESS = 'SERVICE_UPDATE_BY_ID_SUCCESS';
export const SERVICE_UPDATE_BY_ID_FAIL = 'SERVICE_UPDATE_BY_ID_FAIL';
export const SERVICE_UPDATE_BY_ID_RESET = 'SERVICE_UPDATE_BY_ID_RESET';

export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_DELETE_FAIL = 'SERVICE_DELETE_FAIL';

////////////// Service Image ///////////////////
export const SERVICE_IMAGE_NEW_REQUEST = 'SERVICE_IMAGE_NEW_REQUEST';
export const SERVICE_IMAGE_NEW_SUCCESS = 'SERVICE_IMAGE_NEW_SUCCESS';
export const SERVICE_IMAGE_NEW_FAIL = 'SERVICE_IMAGE_NEW_FAIL';
export const SERVICE_IMAGE_NEW_RESET = 'SERVICE_IMAGE_NEW_RESET';

export const SERVICE_IMAGE_DELETE_REQUEST = 'SERVICE_IMAGE_DELETE_REQUEST';
export const SERVICE_IMAGE_DELETE_SUCCESS = 'SERVICE_IMAGE_DELETE_SUCCESS';
export const SERVICE_IMAGE_DELETE_FAIL = 'SERVICE_IMAGE_DELETE_FAIL';
export const SERVICE_IMAGE_DELETE_RESET = 'SERVICE_IMAGE_DELETE_RESET';
