export const SUB_MENU_CAT_NEW_REQUEST = 'SUB_MENU_CAT_NEW_REQUEST';
export const SUB_MENU_CAT_NEW_SUCCESS = 'SUB_MENU_CAT_NEW_SUCCESS';
export const SUB_MENU_CAT_NEW_FAIL = 'SUB_MENU_CAT_NEW_FAIL';
export const SUB_MENU_CAT_NEW_RESET = 'SUB_MENU_CAT_NEW_RESET';

export const SUB_MENU_CAT_ALL_REQUEST = 'SUB_MENU_CAT_ALL_REQUEST';
export const SUB_MENU_CAT_ALL_SUCCESS = 'SUB_MENU_CAT_ALL_SUCCESS';
export const SUB_MENU_CAT_ALL_FAIL = 'SUB_MENU_CAT_ALL_FAIL';

export const SUB_MENU_CAT_BY_ID_REQUEST = 'SUB_MENU_CAT_BY_ID_REQUEST';
export const SUB_MENU_CAT_BY_ID_SUCCESS = 'SUB_MENU_CAT_BY_ID_SUCCESS';
export const SUB_MENU_CAT_BY_ID_FAIL = 'SUB_MENU_CAT_BY_ID_FAIL';
export const SUB_MENU_CAT_BY_ID_RESET = 'SUB_MENU_CAT_BY_ID_RESET';

export const SUB_MENU_CAT_UPDATE_BY_ID_REQUEST =
  'SUB_MENU_CAT_UPDATE_BY_ID_REQUEST';
export const SUB_MENU_CAT_UPDATE_BY_ID_SUCCESS =
  'SUB_MENU_CAT_UPDATE_BY_ID_SUCCESS';
export const SUB_MENU_CAT_UPDATE_BY_ID_FAIL = 'SUB_MENU_CAT_UPDATE_BY_ID_FAIL';
export const SUB_MENU_CAT_UPDATE_BY_ID_RESET =
  'SUB_MENU_CAT_UPDATE_BY_ID_RESET';

export const SUB_MENU_CAT_DELETE_REQUEST = 'SUB_MENU_CAT_DELETE_REQUEST';
export const SUB_MENU_CAT_DELETE_SUCCESS = 'SUB_MENU_CAT_DELETE_SUCCESS';
export const SUB_MENU_CAT_DELETE_FAIL = 'SUB_MENU_CAT_DELETE_FAIL';
